version: "3.8"

services:
  frontend:
    container_name: def_vnode_app
    build: .
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    volumes:
      - './app:/usr/frontend'